In [74]:
import numpy as np

#import pandas as pd

#df = pd.read_csv('data.csv')

In [56]:
A = np.array([[1, 1, 1],
              [1, 2, 2],
              [1, 2, 3]], dtype=float)

In [57]:
A

array([[1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 3.]])

In [58]:
from sympy import Matrix

In [59]:
A_m = Matrix(A)

In [60]:
col_space = A_m.columnspace()

In [61]:
col_space

[Matrix([
 [1.0],
 [1.0],
 [1.0]]),
 Matrix([
 [1.0],
 [2.0],
 [2.0]]),
 Matrix([
 [1.0],
 [2.0],
 [3.0]])]

In [62]:
R_A=np.array(col_space)

In [63]:
R_A

array([[[1.00000000000000],
        [1.00000000000000],
        [1.00000000000000]],

       [[1.00000000000000],
        [2.00000000000000],
        [2.00000000000000]],

       [[1.00000000000000],
        [2.00000000000000],
        [3.00000000000000]]], dtype=object)

In [64]:
n = A.shape[1]
print(n)

3


In [65]:
for j in range(n):

   for k in range(j):
      A[:, j] = A[:, j] - np.dot(A[:, k], A[:, j]) * A[:, k]
   A[:, j] = A[:, j] / np.linalg.norm(A[:, j])
 
print(A)

[[ 5.77350269e-01 -8.16496581e-01 -3.14018492e-16]
 [ 5.77350269e-01  4.08248290e-01 -7.07106781e-01]
 [ 5.77350269e-01  4.08248290e-01  7.07106781e-01]]


In [66]:
Q=A

In [67]:
Q.shape

(3, 3)

In [70]:
QT=Q.transpose()
print(QT)

[[ 5.77350269e-01  5.77350269e-01  5.77350269e-01]
 [-8.16496581e-01  4.08248290e-01  4.08248290e-01]
 [-3.14018492e-16 -7.07106781e-01  7.07106781e-01]]


In [72]:
r=QT*A
print(r)

[[ 3.33333333e-01 -4.71404521e-01 -1.81298661e-16]
 [-4.71404521e-01  1.66666667e-01 -2.88675135e-01]
 [-1.81298661e-16 -2.88675135e-01  5.00000000e-01]]
